# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(size=(7, 7))
tensor, tensor.shape


(tensor([[0.1602, 0.2858, 0.0899, 0.4287, 0.2767, 0.2565, 0.9096],
         [0.9368, 0.1491, 0.5586, 0.0872, 0.3620, 0.2858, 0.9727],
         [0.2465, 0.2624, 0.5238, 0.6602, 0.6262, 0.5220, 0.3043],
         [0.9665, 0.7476, 0.9880, 0.1678, 0.3185, 0.1436, 0.0614],
         [0.5772, 0.0026, 0.3788, 0.2151, 0.5658, 0.7893, 0.8034],
         [0.4099, 0.6401, 0.6069, 0.8443, 0.1089, 0.4710, 0.7372],
         [0.3179, 0.7167, 0.1297, 0.1711, 0.9396, 0.9847, 0.4279]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_1 = torch.rand(size=(1, 7))

# Perform matrix multiplication 
torch.matmul(tensor, tensor_1.T)

tensor([[1.5735],
        [2.2042],
        [1.7904],
        [1.7193],
        [2.1315],
        [2.4517],
        [1.6449]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor = torch.rand([7, 7])
tensor_1 = torch.rand([1, 7])

# Matrix multiply tensors
torch.matmul(tensor, tensor_1.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
cuda_seed = 1234
torch.cuda.manual_seed(cuda_seed)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
random_seed = 42
torch.cuda.manual_seed(random_seed)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU

tensor_2 = torch.rand([2, 3]).to(device)
tensor_3 = torch.rand([2, 3]).to(device)
tensor_2, tensor_3


Device: cuda


(tensor([[0.5932, 0.1123, 0.1535],
         [0.2417, 0.7262, 0.7011]], device='cuda:0'),
 tensor([[0.2038, 0.6511, 0.7745],
         [0.4369, 0.5191, 0.6159]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [7]:
# Perform matmul on tensor_A and tensor_B
tensor_4 = torch.matmul(tensor_2, tensor_3.T)
tensor_4, tensor_4.shape

(tensor([[0.3129, 0.4120],
         [1.0651, 0.9143]], device='cuda:0'), torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [8]:
# Find max
print(tensor.max())
# Find min
print(tensor.min())

tensor(0.9527)
tensor(0.0223)


### 9. Find the maximum and minimum index values of the output of 7.

In [9]:
# Find arg max
print(tensor.argmax())

# Find arg min
print(tensor.argmin())

tensor(26)
tensor(12)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [10]:
# Set seed
torch.manual_seed(7)


# Create random tensor
tensor_A = torch.rand([1, 1, 1, 10])

# Remove single dimensions
tensor_B = tensor_A.squeeze()
# Print out tensors and their shapes

print(tensor_A, tensor_A.shape)

print(tensor_B, tensor_B.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
